# Generated by Django 2.1.15 on 2020-10-28 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('distance', models.FloatField()),
                ('time', models.DateTimeField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('distance', models.FloatField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('total_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkiRacing.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='racer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkiRacing.Racer'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='race_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkiRacing.Race'),
        ),
    ]
